### PR TITLE
New: [AEA-4540] - Add secret scanning

### PR DESCRIPTION
**Pull request by wildjames**
## Summary

- :sparkles: New Feature

### Details

Add a step which runs the secret scanning container given [here](https://github.com/NHSDigital/software-engineering-quality-framework/blob/main/tools/nhsd-git-secrets/nhsd-git-secrets.dockerfile)

### CODE REVIEW

**Comment by wildjames** [comment]
The dockerfile is a minimally tweaked version of [this](https://github.com/NHSDigital/software-engineering-quality-framework/blob/main/tools/nhsd-git-secrets/nhsd-git-secrets.dockerfile) image, which runs some external scripts.

**Comment by wildjames** [comment]
Example of finding a secret: https://github.com/NHSDigital/validation-service-fhir-r4/actions/runs/11498372745/job/32004031045
Example after adding `github-token: ?"?\$\{\{\s*secrets\.GITHUB_TOKEN\s*\}\}"?` to ignore file: https://github.com/NHSDigital/validation-service-fhir-r4/actions/runs/11498452304/job/32004276919?pr=192

**Comment by wildjames** [comment]
Added a pre-commit hook to the devcontainer. 
image

**Comment by wildjames** [comment]
Example of pre-commit failing
image

**Review by jonathanwelch1-nhs — APPROVED** [review]

**Pull request merged**
